In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Sat Apr 10 13:49:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
My_data = [[1,2],[3,4]]

In [ ]:
type(My_data)

list

In [ ]:
np.array(My_data)

In [ ]:
np.asarray(My_data)

array([[1, 2],
       [3, 4]])

In [ ]:
My_data = torch.tensor(My_data)

In [ ]:
type(My_data)

torch.Tensor

In [ ]:
My_data.dtype

torch.int64

In [ ]:
my_nparry = np.random.rand(4,4)

In [ ]:
my_nparry

array([[0.75700886, 0.79177097, 0.50163349, 0.77683496],
       [0.16940862, 0.39282821, 0.05122972, 0.3658047 ],
       [0.57981707, 0.3512923 , 0.31286968, 0.35663935],
       [0.04177011, 0.26773854, 0.43275002, 0.26295139]])

In [ ]:
torch.tensor(my_nparry)

tensor([[0.7570, 0.7918, 0.5016, 0.7768],
        [0.1694, 0.3928, 0.0512, 0.3658],
        [0.5798, 0.3513, 0.3129, 0.3566],
        [0.0418, 0.2677, 0.4328, 0.2630]], dtype=torch.float64)

In [ ]:
torch.from_numpy(my_nparry)

tensor([[0.7570, 0.7918, 0.5016, 0.7768],
        [0.1694, 0.3928, 0.0512, 0.3658],
        [0.5798, 0.3513, 0.3129, 0.3566],
        [0.0418, 0.2677, 0.4328, 0.2630]], dtype=torch.float64)

In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
my_tensor = torch.rand(4,5)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
my_tensor.device

device(type='cpu')

In [ ]:
my_tensor = my_tensor.to("cuda")

In [ ]:
my_tensor.device

device(type='cuda', index=0)

In [ ]:
my_tensor

tensor([[0.0406, 0.6452, 0.9696, 0.2992, 0.6099],
        [0.5450, 0.4180, 0.3526, 0.4744, 0.3466],
        [0.4452, 0.9269, 0.9607, 0.1622, 0.1501],
        [0.1203, 0.7336, 0.0243, 0.3804, 0.5341]], device='cuda:0')

In [ ]:
my_tensor[:3,1:4]

tensor([[0.6452, 0.9696, 0.2992],
        [0.4180, 0.3526, 0.4744],
        [0.9269, 0.9607, 0.1622]], device='cuda:0')

In [ ]:
my_tensor_one = torch.rand(2,2)
my_tensor_two = torch.rand(2,2)

print(my_tensor_one)
my_tensor_two

tensor([[0.3534, 0.3293],
        [0.2723, 0.6825]])


tensor([[0.6590, 0.4417],
        [0.0534, 0.3420]])

In [ ]:
my_tensor_one.mul(my_tensor_two)

tensor([[0.2329, 0.1455],
        [0.0145, 0.2334]])

In [ ]:
my_tensor_one * my_tensor_two

tensor([[0.2329, 0.1455],
        [0.0145, 0.2334]])

In [ ]:
my_tensor_one.matmul(my_tensor_two.T)

tensor([[0.3783, 0.1315],
        [0.4809, 0.2479]])

In [ ]:
torch.matmul(my_tensor_one, my_tensor_two)

tensor([[0.2505, 0.2687],
        [0.2159, 0.3537]])

In [ ]:
my_tensor_one.sum()

tensor(1.6375)

In [ ]:
my_tensor_one.sum(axis=1)

tensor([0.6827, 0.9548])

In [ ]:
torch.max(my_tensor)

tensor(0.9696, device='cuda:0')

In [ ]:
torch.min(my_tensor)

tensor(0.0243, device='cuda:0')

In [ ]:
my_tensor.max()

tensor(0.9696, device='cuda:0')

In [ ]:
torch.cat([my_tensor_one,my_tensor_two])

tensor([[0.3534, 0.3293],
        [0.2723, 0.6825],
        [0.6590, 0.4417],
        [0.0534, 0.3420]])

In [ ]:
torch.cat([my_tensor_one,my_tensor_two], axis =1) # concatination on the coloumn

tensor([[0.3534, 0.3293, 0.6590, 0.4417],
        [0.2723, 0.6825, 0.0534, 0.3420]])

In [ ]:
torch.cat([my_tensor_one,my_tensor_two], dim =1) # concatination on the coloumn

tensor([[0.3534, 0.3293, 0.6590, 0.4417],
        [0.2723, 0.6825, 0.0534, 0.3420]])

In [ ]:
torch.nn.functional.softmax(my_tensor_one, dim=0)

tensor([[0.5203, 0.4126],
        [0.4797, 0.5874]])

In [ ]:
my_tensor.shape

torch.Size([4, 5])

In [ ]:
my_tensor_one.size()

torch.Size([2, 2])

In [ ]:
torch.rand(10,3,128,128)

tensor([[[[0.7844, 0.0196, 0.8627,  ..., 0.2503, 0.3359, 0.0306],
          [0.1145, 0.7135, 0.4191,  ..., 0.7274, 0.5186, 0.2781],
          [0.8114, 0.2155, 0.8351,  ..., 0.2957, 0.5641, 0.6457],
          ...,
          [0.8682, 0.0785, 0.2252,  ..., 0.7657, 0.8486, 0.5850],
          [0.3539, 0.7460, 0.8083,  ..., 0.8618, 0.9947, 0.4583],
          [0.7532, 0.8457, 0.0131,  ..., 0.0376, 0.8339, 0.6343]],

         [[0.9473, 0.7986, 0.9125,  ..., 0.2829, 0.1858, 0.7257],
          [0.8284, 0.1456, 0.6366,  ..., 0.6426, 0.2113, 0.9159],
          [0.4237, 0.4396, 0.4355,  ..., 0.5070, 0.2554, 0.2469],
          ...,
          [0.3683, 0.6426, 0.3881,  ..., 0.5719, 0.4459, 0.9857],
          [0.8708, 0.0096, 0.9122,  ..., 0.9743, 0.7528, 0.0714],
          [0.8990, 0.3193, 0.7175,  ..., 0.1561, 0.2568, 0.3105]],

         [[0.2629, 0.3660, 0.7604,  ..., 0.7065, 0.8888, 0.4314],
          [0.0925, 0.2294, 0.6705,  ..., 0.4163, 0.9627, 0.9819],
          [0.3957, 0.3066, 0.7344,  ..., 0

In [ ]:
my_tensor_one

tensor([[0.3534, 0.3293],
        [0.2723, 0.6825]])

In [ ]:
my_tensor_one.clip(0.3,0.5)

tensor([[0.3534, 0.3293],
        [0.3000, 0.5000]])

In [ ]:
my_tensor_one.cpu().detach().numpy()

array([[0.35340738, 0.32933348],
       [0.27233607, 0.68246967]], dtype=float32)